import { commands, type ExtentDto, type Result } from "./bindings";
import { invokeIpc, reportIpcError } from "./ipc";
import type {
  AppStateDto,
  OziMetadataDto,
  TrackDetail,
  WaypointData,
  SimplifiedPreview,
} from "./types";

// Every typed command delegates to the generated tauri-specta bindings
// (`src/lib/bindings.ts`, regenerated by `cargo test typescript_bindings`).
// Each wrapper preserves its historical signature (bigint IDs in, plain
// values out), converts bigint args to JSON-safe numbers at the boundary,
// and unwraps the bindings' `Result`: backend rejections surface as a sticky
// `data-testid="ipc-error"` toast in dev builds (see `reportIpcError` in
// `src/lib/ipc.ts`) and then rethrow, so call sites keep their `try/catch`
// semantics. User-facing `toast.error("Failed to …")` calls at call sites
// continue to render.
//
// The three raw-byte tile commands at the bottom keep the untyped
// `invokeIpc` path — they are intentionally not in the generated bindings.

/**
 * Unwrap a bindings `Result`, reporting failures via the dev IPC-error
 * toast before rethrowing. `command` is the wire-level command name so the
 * toast title matches what the backend logs.
 */
async function unwrap<T>(
  command: string,
  invocation: Promise<Result<T, string>>,
): Promise<T> {
  let result: Result<T, string>;
  try {
    result = await invocation;
  } catch (error) {
    // The generated bindings rethrow `Error` instances (e.g. transport
    // failures) instead of folding them into the `Result`.
    reportIpcError(command, error);
    throw error;
  }
  if (result.status === "error") {
    reportIpcError(command, result.error);
    throw result.error;
  }
  return result.data;
}

const MAX_SAFE_BIGINT = BigInt(Number.MAX_SAFE_INTEGER);
const MIN_SAFE_BIGINT = BigInt(Number.MIN_SAFE_INTEGER);

/**
 * Convert a bigint ID to the JSON number the wire expects. IDs are small
 * u64 counters; a bigint outside the safe-integer range must never be
 * silently truncated, so it throws a descriptive error instead.
 */
function toIdNumber(id: bigint): number {
  if (id > MAX_SAFE_BIGINT || id < MIN_SAFE_BIGINT) {
    throw new Error(
      `IPC argument bigint ${id.toString()} exceeds Number.MAX_SAFE_INTEGER ` +
        "and cannot be losslessly converted to a JSON number",
    );
  }
  return Number(id);
}

export async function getAppState(): Promise<AppStateDto> {
  return unwrap("get_app_state", commands.getAppState());
}

export async function getTracksGeojson(): Promise<GeoJSON.FeatureCollection> {
  const geojson = await unwrap(
    "get_tracks_geojson",
    commands.getTracksGeojson(),
  );
  return geojson as unknown as GeoJSON.FeatureCollection;
}

export async function loadProjects(): Promise<void> {
  await unwrap("load_projects", commands.loadProjects());
}

/**
 * Begin downloading a LizaAlert project bundle.
 *
 * Returns immediately with a `download_id` that callers use to correlate
 * `download-progress` / `bundle-file-ready` / `bundle-progress` events and
 * to cancel via {@link cancelDownload}. The actual download proceeds on a
 * background task — the returned promise resolves once the Tauri command
 * handler returns, NOT once the bundle has finished downloading. Callers
 * MUST NOT `await` the download via this promise; subscribe to events
 * instead so the main thread stays responsive.
 */
export async function loadProject(slug: string): Promise<string> {
  return unwrap("load_project", commands.loadProject(slug));
}

/**
 * Fetch a bundle's map list WITHOUT downloading anything. The backend
 * updates `current_project` and emits `state-changed`; the maps column
 * re-renders from the `currentProject` store. Works even while the
 * project catalog itself is still refreshing. The actual download starts
 * only via {@link loadProject} (the explicit "Open bundle" affordance).
 */
export async function previewProject(slug: string): Promise<void> {
  await unwrap("preview_project", commands.previewProject(slug));
}

/**
 * Abort an in-flight bundle download. Returns `true` if the download was
 * known and a cancel signal was delivered; files already on disk remain
 * untouched and a subsequent {@link loadProject} for the same bundle will
 * resume by fetching only the missing files.
 */
export async function cancelDownload(downloadId: string): Promise<boolean> {
  return unwrap("cancel_download", commands.cancelDownload(downloadId));
}

/**
 * Open a map. Returns the download id when the map had to be fetched, or an
 * empty string when it opened from disk — the caller shows progress for it.
 */
export async function openSelectedMap(mapName: string): Promise<string> {
  return await unwrap("open_selected_map", commands.openSelectedMap(mapName));
}

export async function openLocalBundle(dir: string): Promise<string> {
  return unwrap("open_local_bundle", commands.openLocalBundle(dir));
}

export async function setBundlesRoot(path: string): Promise<void> {
  await unwrap("set_bundles_root", commands.setBundlesRoot(path));
}

export async function saveProject(path: string): Promise<void> {
  await unwrap("save_project", commands.saveProject(path));
}

export async function loadProjectFile(path: string): Promise<void> {
  await unwrap("load_project_file", commands.loadProjectFile(path));
}

export async function importGpx(path: string): Promise<string> {
  return unwrap("import_gpx", commands.importGpx(path));
}

export async function importPlt(path: string): Promise<string> {
  return unwrap("import_plt", commands.importPlt(path));
}

/**
 * Recursively import every GPX/PLT file under `path` (per-date subfolders
 * included). Returns a human-readable summary string — per-file failures
 * are folded into the summary, not thrown.
 */
export async function importTracksDirectory(path: string): Promise<string> {
  return unwrap(
    "import_tracks_directory",
    commands.importTracksDirectory(path),
  );
}

/**
 * Show or hide every track in one call.
 *
 * Triage looks at one track at a time, so the alternative — a toggle per row —
 * costs one round trip and one state-changed event per track.
 */
export async function setAllTracksVisible(visible: boolean): Promise<void> {
  await unwrap("set_all_tracks_visible", commands.setAllTracksVisible(visible));
}

/** Leave one track visible and hide the rest. */
export async function showOnlyTrack(
  layerId: bigint,
  trackId: bigint,
): Promise<void> {
  await unwrap(
    "show_only_track",
    commands.showOnlyTrack(toIdNumber(layerId), toIdNumber(trackId)),
  );
}

export async function exportGpx(layerId: bigint, path: string): Promise<void> {
  await unwrap("export_gpx", commands.exportGpx(toIdNumber(layerId), path));
}

export async function getTrackExportDefaultPath(
  trackName: string,
  extension: "gpx" | "plt",
): Promise<string | null> {
  return unwrap(
    "get_track_export_default_path",
    commands.getTrackExportDefaultPath(trackName, extension),
  );
}

export async function exportTrackPlt(
  layerId: bigint,
  trackId: bigint,
  path: string,
): Promise<void> {
  await unwrap(
    "export_track_plt",
    commands.exportTrackPlt(toIdNumber(layerId), toIdNumber(trackId), path),
  );
}

export async function exportWptWaypoints(
  layerId: bigint,
  path: string,
): Promise<void> {
  await unwrap(
    "export_wpt_waypoints",
    commands.exportWptWaypoints(toIdNumber(layerId), path),
  );
}

export async function getWptExportDefaultPath(
  layerId: bigint,
): Promise<string | null> {
  return unwrap(
    "get_wpt_export_default_path",
    commands.getWptExportDefaultPath(toIdNumber(layerId)),
  );
}

export async function undo(): Promise<void> {
  await unwrap("undo", commands.undo());
}

export async function redo(): Promise<void> {
  await unwrap("redo", commands.redo());
}

export async function renameTrack(
  layerId: bigint,
  trackId: bigint,
  newName: string,
): Promise<void> {
  await unwrap(
    "rename_track",
    commands.renameTrack(toIdNumber(layerId), toIdNumber(trackId), newName),
  );
}

export async function setTrackColor(
  layerId: bigint,
  trackId: bigint,
  color: [number, number, number, number],
): Promise<void> {
  await unwrap(
    "set_track_color",
    commands.setTrackColor(toIdNumber(layerId), toIdNumber(trackId), color),
  );
}

export async function toggleTrackVisible(
  layerId: bigint,
  trackId: bigint,
): Promise<void> {
  await unwrap(
    "toggle_track_visible",
    commands.toggleTrackVisible(toIdNumber(layerId), toIdNumber(trackId)),
  );
}

export async function toggleWaypointVisible(
  layerId: bigint,
  waypointId: bigint,
): Promise<void> {
  await unwrap(
    "toggle_waypoint_visible",
    commands.toggleWaypointVisible(toIdNumber(layerId), toIdNumber(waypointId)),
  );
}

/** Show or hide every waypoint in the project in one command. */
export async function setAllWaypointsVisible(visible: boolean): Promise<void> {
  await unwrap(
    "set_all_waypoints_visible",
    commands.setAllWaypointsVisible(visible),
  );
}

/** Leave one waypoint visible and hide the rest. */
export async function showOnlyWaypoint(
  layerId: bigint,
  waypointId: bigint,
): Promise<void> {
  await unwrap(
    "show_only_waypoint",
    commands.showOnlyWaypoint(toIdNumber(layerId), toIdNumber(waypointId)),
  );
}

export async function revealBundle(): Promise<void> {
  await unwrap("reveal_bundle", commands.revealBundle());
}

export async function getOziMetadata(mapPath: string): Promise<OziMetadataDto> {
  const metadata = await unwrap(
    "get_ozi_metadata",
    commands.getOziMetadata(mapPath),
  );
  return metadata as unknown as OziMetadataDto;
}

/** Return raw tile bytes from SQLite bundle. Used by sqlite-protocol.ts. */
export async function getSqliteTile(
  path: string,
  baseZoom: number,
  z: number,
  x: number,
  y: number,
): Promise<ArrayBuffer> {
  return invokeIpc("get_sqlite_tile", { path, baseZoom, z, x, y });
}

/** Return PNG-encoded tile bytes from OZF2 file. Used by ozi-protocol.ts. */
export async function getOziTile(
  mapPath: string,
  level: number,
  tileX: number,
  tileY: number,
): Promise<ArrayBuffer> {
  return invokeIpc("get_ozi_tile", { mapPath, level, tileX, tileY });
}

/** Return a 256×256 PNG for Web Mercator tile (tx, ty, tz) reprojected from OZF2. */
export async function getOziTileProjected(
  mapPath: string,
  tx: number,
  ty: number,
  tz: number,
): Promise<ArrayBuffer> {
  return invokeIpc("get_ozi_tile_projected", { mapPath, tx, ty, tz });
}

export async function moveTrackPoint(
  layerId: bigint,
  trackId: bigint,
  segmentId: bigint,
  pointId: bigint,
  position: [number, number],
): Promise<void> {
  await unwrap(
    "move_track_point",
    commands.moveTrackPoint(
      toIdNumber(layerId),
      toIdNumber(trackId),
      toIdNumber(segmentId),
      toIdNumber(pointId),
      position,
    ),
  );
}

export async function deleteTrackPoint(
  layerId: bigint,
  trackId: bigint,
  segmentId: bigint,
  pointId: bigint,
): Promise<void> {
  await unwrap(
    "delete_track_point",
    commands.deleteTrackPoint(
      toIdNumber(layerId),
      toIdNumber(trackId),
      toIdNumber(segmentId),
      toIdNumber(pointId),
    ),
  );
}

export async function insertTrackPoint(
  layerId: bigint,
  trackId: bigint,
  segmentId: bigint,
  index: number,
  position: [number, number],
): Promise<void> {
  await unwrap(
    "insert_track_point",
    commands.insertTrackPoint(
      toIdNumber(layerId),
      toIdNumber(trackId),
      toIdNumber(segmentId),
      index,
      position,
    ),
  );
}

export async function splitSegment(
  layerId: bigint,
  trackId: bigint,
  segmentId: bigint,
  pointId: bigint,
): Promise<void> {
  await unwrap(
    "split_segment",
    commands.splitSegment(
      toIdNumber(layerId),
      toIdNumber(trackId),
      toIdNumber(segmentId),
      toIdNumber(pointId),
    ),
  );
}

export async function joinSegments(
  layerId: bigint,
  trackId: bigint,
  segIdA: bigint,
  segIdB: bigint,
): Promise<void> {
  // Wire arg keys are `segmentIdA` / `segmentIdB` (generated from the Rust
  // command signature); the historical local parameter names stay for
  // call-site readability only.
  await unwrap(
    "join_segments",
    commands.joinSegments(
      toIdNumber(layerId),
      toIdNumber(trackId),
      toIdNumber(segIdA),
      toIdNumber(segIdB),
    ),
  );
}

/** Sort every segment's points by timestamp (untimed points keep order). */
export async function sortTrackPoints(
  layerId: bigint,
  trackId: bigint,
): Promise<void> {
  await unwrap(
    "sort_track_points",
    commands.sortTrackPoints(toIdNumber(layerId), toIdNumber(trackId)),
  );
}

/**
 * Remove every point outside `extent` (the current map viewport). Returns
 * the removed-point count; the backend refuses to remove every point.
 */
export async function cropTrackToExtent(
  layerId: bigint,
  trackId: bigint,
  extent: ExtentDto,
): Promise<number> {
  return unwrap(
    "crop_track_to_extent",
    commands.cropTrackToExtent(
      toIdNumber(layerId),
      toIdNumber(trackId),
      extent,
    ),
  );
}

/**
 * Remove points outside the `[from, to]` time range (ISO-8601 UTC strings,
 * either bound optional). Untimed points are always kept. Returns the
 * removed-point count.
 */
export async function cropTrackToTime(
  layerId: bigint,
  trackId: bigint,
  from: string | null,
  to: string | null,
): Promise<number> {
  return unwrap(
    "crop_track_to_time",
    commands.cropTrackToTime(
      toIdNumber(layerId),
      toIdNumber(trackId),
      from,
      to,
    ),
  );
}

export async function deleteTrack(
  layerId: bigint,
  trackId: bigint,
): Promise<void> {
  await unwrap(
    "delete_track",
    commands.deleteTrack(toIdNumber(layerId), toIdNumber(trackId)),
  );
}

export async function deleteWaypoint(
  layerId: bigint,
  waypointId: bigint,
): Promise<void> {
  await unwrap(
    "delete_waypoint",
    commands.deleteWaypoint(toIdNumber(layerId), toIdNumber(waypointId)),
  );
}

export async function renameWaypoint(
  layerId: bigint,
  waypointId: bigint,
  newName: string,
): Promise<void> {
  await unwrap(
    "rename_waypoint",
    commands.renameWaypoint(
      toIdNumber(layerId),
      toIdNumber(waypointId),
      newName,
    ),
  );
}

export async function setWaypointSymbol(
  layerId: bigint,
  waypointId: bigint,
  symbol: string | null,
): Promise<void> {
  await unwrap(
    "set_waypoint_symbol",
    commands.setWaypointSymbol(
      toIdNumber(layerId),
      toIdNumber(waypointId),
      symbol,
    ),
  );
}

export async function simplifyTrack(
  layerId: bigint,
  trackId: bigint,
  tolerance: number,
): Promise<void> {
  await unwrap(
    "simplify_track",
    commands.simplifyTrack(toIdNumber(layerId), toIdNumber(trackId), tolerance),
  );
}

export async function setTrackLineWidth(
  layerId: bigint,
  trackId: bigint,
  width: number,
): Promise<void> {
  await unwrap(
    "set_track_line_width",
    commands.setTrackLineWidth(toIdNumber(layerId), toIdNumber(trackId), width),
  );
}

export async function getTrackDetail(
  layerId: bigint,
  trackId: bigint,
): Promise<TrackDetail> {
  return unwrap(
    "get_track_detail",
    commands.getTrackDetail(toIdNumber(layerId), toIdNumber(trackId)),
  );
}

export async function addWaypoint(
  layerId: bigint,
  lat: number,
  lon: number,
  name: string,
): Promise<void> {
  await unwrap(
    "add_waypoint",
    commands.addWaypoint(toIdNumber(layerId), lat, lon, name),
  );
}

export async function moveWaypoint(
  layerId: bigint,
  waypointId: bigint,
  position: [number, number],
): Promise<void> {
  await unwrap(
    "move_waypoint",
    commands.moveWaypoint(
      toIdNumber(layerId),
      toIdNumber(waypointId),
      position,
    ),
  );
}

export async function getWaypoints(layerId: bigint): Promise<WaypointData[]> {
  return unwrap("get_waypoints", commands.getWaypoints(toIdNumber(layerId)));
}

export async function getSimplifiedPreview(
  layerId: bigint,
  trackId: bigint,
  tolerance: number,
): Promise<SimplifiedPreview> {
  return unwrap(
    "get_simplified_preview",
    commands.getSimplifiedPreview(
      toIdNumber(layerId),
      toIdNumber(trackId),
      tolerance,
    ),
  );
}

export async function createEmptyTrack(
  layerId: bigint,
  name: string,
): Promise<bigint> {
  // The wire value is a JSON number (serde-serialized u64), not a bigint —
  // convert at the boundary so the declared return type holds and strict
  // comparisons against bigint stores (e.g. `$selectedTrackId === trackId`)
  // behave correctly.
  const trackId = await unwrap(
    "create_empty_track",
    commands.createEmptyTrack(toIdNumber(layerId), name),
  );
  return BigInt(trackId);
}
