/* eslint-disable */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppState() : Promise<Result<AppStateDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTracksGeojson() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tracks_geojson") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every track in the project as a row: what the Tracks tab shows, typed, and
 * without the geometry it was paying for. See `list_track_summaries`.
 */
async listTracks() : Promise<Result<TrackSummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tracks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadProjects() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a bundle, downloading what is missing.
 * 
 * `skip` names top-level entries to leave on the server — print sheets and
 * Android tile packs are most of the transfer and this app cannot open them.
 * Nothing is skipped unless the caller names it: the choice is the
 * operator's, not a default this code decides for them.
 */
async loadProject(slug: string, skip: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project", { slug, skip }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview a bundle: fetch its map list without downloading anything.
 * Selecting a project in the loader calls this; the actual download starts
 * only from the explicit open action (`load_project`).
 */
async previewProject(slug: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_project", { slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(downloadId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { downloadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the catalogue refresh that is running.
 * 
 * The walk is up to a thousand pages and holds the application busy for all
 * of it, which on a field link disables the only download button in the app
 * for minutes after launch. Returns whether there was a refresh to stop.
 */
async cancelProjectListing() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_project_listing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a map, downloading it first when it is not on disk.
 * 
 * Returns the download id when a download started, so the caller can show
 * progress for it and cancel it; an empty string when the map opened from
 * disk or the request was a no-op.
 */
async openSelectedMap(mapName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_selected_map", { mapName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLocalBundle(dir: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_local_bundle", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBundlesRoot(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_bundles_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the next search.
 * 
 * A project is one search, and nothing created an empty one until now: a crew
 * that finished an operation and began the next kept adding to the same
 * document. Asking before discarding unsaved work is the caller's job — the
 * frontend already owns that question for the close guard.
 */
async newProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadProjectFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importGpx(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_gpx", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importPlt(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_plt", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import an OziExplorer waypoint file (`.wpt`).
 * 
 * We have written this format since ADR-0022 and never read it, which is the
 * wrong way round: the штаб next door runs the original and hands over `.wpt`.
 */
async importWpt(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wpt", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * CJ-3: recursively import every GPX/PLT under a folder (per-date
 * subfolders included). Per-file failures are reported, not fatal.
 */
async importTracksDirectory(path: string) : Promise<Result<ImportReportDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_tracks_directory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportGpx(layerId: number, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_gpx", { layerId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a day's work — every track and every mark — to one GPX file.
 */
async exportAllTracksGpx(path: string) : Promise<Result<DayExportDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_all_tracks_gpx", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackExportDefaultPath(trackName: string, extension: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_export_default_path", { trackName, extension }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async redo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameTrack(layerId: number, trackId: number, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_track", { layerId, trackId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTrackLayer(name: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_track_layer", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWaypointLayer(name: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_waypoint_layer", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameTrackLayer(layerId: number, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_track_layer", { layerId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWaypointLayer(layerId: number, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_waypoint_layer", { layerId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTrackLayer(layerId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_track_layer", { layerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWaypointLayer(layerId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_waypoint_layer", { layerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackColor(layerId: number, trackId: number, color: [number, number, number, number]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_color", { layerId, trackId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abandon a drawing in progress: reverse its commands without leaving them
 * in the redo stack.
 * 
 * The track is named as well as counted. The undo stack is bounded, so a
 * drawing longer than the stack has already lost the command that created
 * the track, and counting alone left an empty one behind.
 */
async cancelDrawing(layerId: number, trackId: number, commandCount: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_drawing", { layerId, trackId, commandCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleTrackVisible(layerId: number, trackId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_track_visible", { layerId, trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show or hide every track at once — the triage operator's bulk control.
 */
async setAllTracksVisible(visible: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_all_tracks_visible", { visible }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Leave one track visible and hide every other one.
 */
async showOnlyTrack(layerId: number, trackId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_only_track", { layerId, trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show or hide every waypoint at once — the Waypoints tab's bulk control.
 */
async setAllWaypointsVisible(visible: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_all_waypoints_visible", { visible }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Leave one waypoint visible and hide every other one.
 */
async showOnlyWaypoint(layerId: number, waypointId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_only_waypoint", { layerId, waypointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleWaypointVisible(layerId: number, waypointId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_waypoint_visible", { layerId, waypointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveTrackPoint(layerId: number, trackId: number, segmentId: number, pointId: number, position: [number, number]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_track_point", { layerId, trackId, segmentId, pointId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTrackPoint(layerId: number, trackId: number, segmentId: number, pointId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_track_point", { layerId, trackId, segmentId, pointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertTrackPoint(layerId: number, trackId: number, segmentId: number, index: number, position: [number, number]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_track_point", { layerId, trackId, segmentId, index, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async splitSegment(layerId: number, trackId: number, segmentId: number, pointId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("split_segment", { layerId, trackId, segmentId, pointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinSegments(layerId: number, trackId: number, segmentIdA: number, segmentIdB: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_segments", { layerId, trackId, segmentIdA, segmentIdB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTrack(layerId: number, trackId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_track", { layerId, trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWaypoint(layerId: number, lat: number, lon: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_waypoint", { layerId, lat, lon, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveWaypoint(layerId: number, waypointId: number, position: [number, number]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_waypoint", { layerId, waypointId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWaypoint(layerId: number, waypointId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_waypoint", { layerId, waypointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWaypoint(layerId: number, waypointId: number, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_waypoint", { layerId, waypointId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWaypointSymbol(layerId: number, waypointId: number, symbol: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_waypoint_symbol", { layerId, waypointId, symbol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set or clear a waypoint's colour. `None` restores the default rather than
 * setting a colour that happens to look like it.
 */
async setWaypointColor(layerId: number, waypointId: number, color: [number, number, number, number] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_waypoint_color", { layerId, waypointId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the note beside a mark.
 * 
 * The place travels between headquarters; until 2026-09-23 the reason for it
 * did not, in either direction.
 */
async setWaypointDescription(layerId: number, waypointId: number, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_waypoint_description", { layerId, waypointId, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async simplifyTrack(layerId: number, trackId: number, toleranceM: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simplify_track", { layerId, trackId, toleranceM }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * CJ-4: sort every segment's points by timestamp (untimed first, stable).
 * One undoable step; a no-op when the track is already ordered.
 */
async sortTrackPoints(layerId: number, trackId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sort_track_points", { layerId, trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * CJ-4: crop the track to a lat/lon extent (the current map view). Returns
 * how many points were removed; refuses to remove every point.
 */
async cropTrackToExtent(layerId: number, trackId: number, extent: ExtentDto) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("crop_track_to_extent", { layerId, trackId, extent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trim a track at one of its points, keeping that point. `before` cuts what
 * came earlier, otherwise what came later. Returns removed-point count.
 */
async trimTrackAtPoint(layerId: number, trackId: number, pointId: number, before: boolean) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_track_at_point", { layerId, trackId, pointId, before }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * CJ-4: crop the track to a time range (ISO-8601 UTC bounds, either side
 * optional). Untimed points are always kept. Returns removed-point count.
 */
async cropTrackToTime(layerId: number, trackId: number, from: string | null, to: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("crop_track_to_time", { layerId, trackId, from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackLineWidth(layerId: number, trackId: number, width: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_line_width", { layerId, trackId, width }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackDetail(layerId: number, trackId: number) : Promise<Result<TrackDetailDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_detail", { layerId, trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWaypoints(layerId: number) : Promise<Result<WaypointDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_waypoints", { layerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSimplifiedPreview(layerId: number, trackId: number, toleranceM: number) : Promise<Result<SimplifiedPreviewDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_simplified_preview", { layerId, trackId, toleranceM }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revealBundle() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_bundle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show a file the application just wrote, in the system's file manager.
 * 
 * CJ-6 ends with a file being handed to a group, and the last step of that
 * is finding it. `reveal_bundle` only ever showed the active bundle's
 * directory; an export could land anywhere the operator chose, and a path in
 * a toast is not something anybody retypes at four in the morning.
 * 
 * Refuses a path that does not exist rather than opening a window on
 * nothing.
 */
async revealPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportTrackPlt(layerId: number, trackId: number, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_track_plt", { layerId, trackId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWptWaypoints(layerId: number, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_wpt_waypoints", { layerId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a waypoint layer to GPX — the format phones, navigators and the
 * other groups' software read.
 */
async exportGpxWaypoints(layerId: number, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_gpx_waypoints", { layerId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggested file name for a waypoint export in the given format.
 */
async getWaypointsExportDefaultPath(layerId: number, extension: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_waypoints_export_default_path", { layerId, extension }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWptExportDefaultPath(layerId: number) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wpt_export_default_path", { layerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEmptyTrack(layerId: number, name: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_empty_track", { layerId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return tile grid metadata for an OZF2 map (levels, dimensions, georeference coefficients).
 */
async getOziMetadata(mapPath: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ozi_metadata", { mapPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveMapDto = { kind: string; project_name: string; package_name: string; local_path: string; center_lat: number; center_lon: number; base_zoom: number }
export type AppStateDto = { project_name: string; project_saved: boolean; 
/**
 * True when the project has edits not yet persisted to disk (drives the
 * dirty indicator and the close guard, CJ-7).
 */
project_dirty: boolean; 
/**
 * Current .ozp path when the project has been saved/loaded; lets the
 * frontend quick-save (Cmd+S) without a dialog.
 */
project_path: string | null; status: string; 
/**
 * The catalogue walk is running. Blocks another refresh; blocks nothing
 * else — see `LizaAlertState::listing_busy`.
 */
listing_busy: boolean; 
/**
 * A bundle is being downloaded or opened from disk. Blocks another one.
 */
bundle_busy: boolean; downloading_maps: string[]; current_project: LizaProjectDto | null; active_map: ActiveMapDto | null; diagnostics: DiagnosticDto[]; track_layers: LayerSummaryDto[]; waypoint_layers: LayerSummaryDto[]; track_layer_count: number; waypoint_layer_count: number; tracks: TrackSummaryDto[] }
export type BundleEntryDto = { name: string; is_dir: boolean; size_bytes: number | null }
/**
 * What a day's export wrote, so the interface can say it.
 */
export type DayExportDto = { tracks: number; waypoints: number }
export type DiagnosticDto = { level: string; message: string }
/**
 * Lat/lon bounding box for extent crops — the current map viewport.
 */
export type ExtentDto = { min_lat: number; min_lon: number; max_lat: number; max_lon: number }
/**
 * What a folder import did, for the interface to put into words.
 * 
 * This used to be an English sentence built here and toasted verbatim, so a
 * Russian crew read "Imported 12 tracks and 3 waypoints from 4 files" after
 * the most common import there is. Same rule as the bundle progress: the
 * backend sends what happened, the interface says it.
 */
export type ImportReportDto = { files: number; tracks: number; waypoints: number; 
/**
 * Names of the files that could not be read. Names, not paths: a toast
 * has no room for a directory tree and the name is what is recognised.
 */
skipped: string[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LayerSummaryDto = { id: number; name: string }
export type LizaMapPackageDto = { name: string; base_zoom: number; downloaded: boolean; 
/**
 * Size in bytes when known — from the listing for a remote map, from the
 * file for a cached one. `None` is "unknown", not zero.
 */
size_bytes: number | null }
export type LizaProjectDto = { 
/**
 * The bundle's identifier, as `load_project` takes it.
 * 
 * Without it a loader opened on an already-previewed project had a name
 * and no way to ask for that project, so its download button did
 * nothing at all.
 */
slug: string; name: string; center_lat: number; center_lon: number; maps: LizaMapPackageDto[]; 
/**
 * The bundle's top level — what the operator chooses from when deciding
 * what not to download.
 */
contents: BundleEntryDto[] }
export type PointDetailDto = { id: number; lat: number; lon: number; elevation: number | null; timestamp: string | null }
export type SegmentDetailDto = { id: number; points: PointDetailDto[] }
export type SimplifiedPreviewDto = { original_count: number; simplified_count: number; segments: SimplifiedSegmentDto[] }
export type SimplifiedSegmentDto = { id: number; original_count: number; simplified_count: number; kept_points: PointDetailDto[] }
export type TrackDetailDto = { id: number; name: string; segments: SegmentDetailDto[] }
/**
 * Per-track summary surfaced to the UI for the Tracks panel rows.
 * 
 * Includes derived statistics (distance, duration, point count) computed
 * from the domain `Track` so the frontend can render them without re-walking
 * the segment data.
 */
export type TrackSummaryDto = { layer_id: number; track_id: number; name: string; color: string; line_width: number; visible: boolean; distance_km: number; duration_seconds: number | null; point_count: number }
export type WaypointDto = { id: number; name: string; lat: number; lon: number; symbol: string | null; visible: boolean; 
/**
 * RGBA, or absent for "whatever the map draws waypoints with". Absent is
 * not a colour: changing the default later moves every uncoloured
 * waypoint with it.
 */
color: [number, number, number, number] | null; 
/**
 * The note beside the mark: what a crew is actually sent to.
 */
description: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
