// DTO type surface for the frontend.
//
// Wire-shape DTOs are generated by tauri-specta from the Rust command
// registry into `src/lib/bindings.ts` (regenerated via
// `cargo test typescript_bindings`; never edited by hand). The re-exports
// below alias them under their historical frontend names so the generated
// file is the ONE source of truth for everything serde puts on the wire.
// Types with no generated counterpart — event payloads and frontend-only
// shapes — remain declared locally.

// Invariant carried over from the layers spec (`auto-create-default-layers`
// change): whenever `AppStateDto.current_project` is non-null, both
// `track_layers` and `waypoint_layers` contain at least one entry — a
// default "Tracks" / "Waypoints" layer is appended by the backend at
// project construction and load-path normalization. Frontend handlers that
// run only while a project is open MAY treat the derived
// `activeTrackLayerId` / `activeWaypointLayerId` stores as non-null.
export type {
  ActiveMapDto,
  AppStateDto,
  DiagnosticDto,
  LizaMapPackageDto,
  LizaProjectDto,
} from "./bindings";

/**
 * One row of the LizaAlert catalogue.
 *
 * Hand-written rather than generated: the catalogue travels only as the
 * `projects-chunk` event payload, and specta generates types for command
 * signatures, not for events. It left the generated bindings when it left
 * `AppStateDto` — which it did because the state snapshot is fetched on every
 * `state-changed`, and thirteen thousand rows is not a state snapshot.
 *
 * Mirrors `LizaProjectSummaryDto` in `src-tauri/src/commands/mod.rs`; keep the
 * two in step by hand, as `CLAUDE.md` requires for this file.
 */
export interface LizaProjectSummaryDto {
  slug: string;
  name: string;
  /** Whether this bundle is already on disk and openable offline. */
  cached: boolean;
}

// Generated DTOs re-exported under their historical frontend names.
// `TrackSummary.duration_seconds` is null when none of the track points
// carry timestamps, in which case the UI must omit the duration segment.
export type {
  PointDetailDto as PointDetail,
  SegmentDetailDto as SegmentDetail,
  SimplifiedPreviewDto as SimplifiedPreview,
  SimplifiedSegmentDto as SimplifiedSegmentPreview,
  TrackDetailDto as TrackDetail,
  TrackSummaryDto as TrackSummary,
  WaypointDto as WaypointData,
} from "./bindings";

import type { LayerSummaryDto as GeneratedLayerSummaryDto } from "./bindings";

/**
 * Generated wire shape plus an optional per-layer visibility flag. The
 * backend does not send `visible` today; when absent the layer is treated
 * as visible (see `selectVisibleWaypointLayers`). Reserved for future
 * per-layer toggling — the flag is frontend-only, so it extends the
 * generated type instead of editing `bindings.ts`.
 */
export type LayerSummaryDto = GeneratedLayerSummaryDto & {
  visible?: boolean;
};

/**
 * Persisted shape of the LizaAlert project catalog cache (see
 * `cache-project-catalog-locally` change). Stored as JSON under the
 * versioned `localStorage` key `liza:projects:v1`.
 */
export interface CatalogCachePayload {
  items: LizaProjectSummaryDto[];
  /** ISO-8601 UTC timestamp written at `saveCatalogCache` time. */
  writtenAt: string;
}

// `get_ozi_metadata` returns `JsonValue` in the generated bindings (the Rust
// side responds with dynamic JSON), so the OZI metadata shapes stay local.
export interface OziLevelDto {
  level_index: number;
  width: number;
  height: number;
  tile_width: number;
  tile_height: number;
  tile_columns: number;
  tile_rows: number;
}

export interface OziMetadataDto {
  map_path: string;
  title: string;
  projection: string;
  datum: string;
  calibration_points: string[];
  levels: OziLevelDto[];
  bounds: [number, number, number, number] | null;
  native_zoom: number;
  min_zoom: number;
}

// Event payloads (Tauri event channel, not command responses) have no
// generated counterpart and stay hand-written.

export interface DownloadProgressPayload {
  download_id: string;
  package_name: string;
  downloaded_bytes: number;
  total_bytes?: number;
  /** Zero-based position of this file within the prefix-sorted bundle. */
  file_index?: number;
  /** Total number of files in the bundle. */
  file_count?: number;
}

export interface BundleProgressPayload {
  download_id: string;
  /**
   * The backend's English wording. Shown only when the interface has no
   * translation for `message_key` — it is the fallback, not the text.
   */
  message: string;
  /** Translation key and its arguments in order, positional as `{0}`, `{1}`. */
  message_key: string;
  message_args: string[];
  phase: "scanning" | "downloading" | "extracting" | "indexing";
  completed?: number;
  total?: number;
  downloaded_bytes?: number;
  total_bytes?: number;
}

/** Emitted once by whichever path owns a download, when it stops running. */
export interface DownloadFinishedPayload {
  download_id: string;
  ok: boolean;
  message?: string | null;
}

/** Emitted once a single file inside a bundle has been fully written to disk. */
export interface BundleFileReadyPayload {
  download_id: string;
  package_name: string;
  local_path: string;
  file_index: number;
  file_count: number;
}
